### ISSUE TITLE
When using the docker distribution, npx generator for nuxt fails

### ISSUE THREAD

**Issue by HugoFerrant** [api-platform/docs#1300]
```
/usr/src/pwa # npx @api-platform/client-generator https://caddy. --generator nuxt

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/636/lib/node_modules/@api-platform/client-generator/node_modules/highlight.js/deprecated.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! highlight.js@9.18.5 postinstall: `node deprecated.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the highlight.js@9.18.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-01T11_26_29_592Z-debug.log
Install for [ '@api-platform/client-generator@latest' ] failed with code 1
```

**Comment by HugoFerrant** [comment]
after some time, I figured out we should maybe use the binary directly with `generate-api-platform-client https://caddy . --generator nuxt`

**Comment by HugoFerrant** [comment]
I'll open a PR to the doc (eventually with other issues I found in the nuxt part). I keep the issue open until this, as the doc is not OK atm
